## Numpy Array Oluşturma Yöntemleri

In [1]:
data_list = [1,2,3]

In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [7]:
arr2 = np.array(data_list2)

In [8]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr

array([1, 2, 3])

In [10]:
arr[1]

2

In [11]:
arr[2]

3

In [12]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
arr2[2,2]

90

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0,100,5) # 0 ile 100 arası değerleri 5 parçaya böler.

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
np.eye(6) # Birim Matris Oluşturur.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.randint(0,10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

3

In [27]:
np.random.randint(10) # 0(dahil) ile 10(hariç) arasında random int oluşturur.

7

In [28]:
np.random.randint(1,10,5) # 1(dahil) ile 10(hariç) arasında 5 değer oluşturarak 5 değer saklayan array oluşturur.

array([8, 7, 7, 9, 8])

In [30]:
np.random.rand(5) # 0 ile 1 arasında 5 float değerler oluşturur.

array([0.1311822 , 0.40126997, 0.72142335, 0.2367072 , 0.15839186])

In [31]:
np.random.randn(10) # 0 etrafında - ve + değerlerle Gaussian Distribution'a göre değerler oluşturur.

array([-1.73177265, -0.51965932,  0.26229035,  0.62214498,  2.37086873,
        0.32317969, -0.19989248,  2.11537942, -1.64791316,  1.50424414])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5) # 5 x 5 =  25 tek boyutlu matrisi 2 boyuta çevirir.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.reshape(4,5) # 4 x 5 25'e eşit olmadığından çeviremez ve hata verir.

ValueError: cannot reshape array of size 25 into shape (4,5)

In [36]:
newArray = np.random.randint(1,100,10)

In [37]:
newArray

array([14, 22, 87, 79, 42, 61, 50, 77, 27, 85])

In [38]:
newArray.max()

87

In [39]:
newArray.min()

14

In [40]:
newArray.sum() # Tüm değerlerin toplamı

544

In [41]:
newArray.mean() # Ortalama Bulur

54.4

In [42]:
newArray.argmin() # En küçük eleman 6.indekste

0

In [43]:
newArray.argmax() # En büyük eleman 7.indekste

2

**Tekrar ve Determinant Hesaplama**

In [45]:
detArray =  np.random.randint(1,100,25)

In [46]:
detArray

array([65, 35, 90,  8, 99, 19, 27, 13, 51,  6, 57,  6, 94, 28, 25, 53,  7,
       90, 81, 68, 32, 22, 85,  3, 13])

In [47]:
detArray = detArray.reshape(5,5)

In [48]:
detArray

array([[65, 35, 90,  8, 99],
       [19, 27, 13, 51,  6],
       [57,  6, 94, 28, 25],
       [53,  7, 90, 81, 68],
       [32, 22, 85,  3, 13]])

In [49]:
np.linalg.det(detArray)

465975203.99999976

In [50]:
round(np.linalg.det(detArray))

465975204

In [51]:
detArray2 = np.array([[1,2],[3,4]])

In [52]:
round(np.linalg.det(detArray2))

-2