**Numpy Array Indekslenmesi ve Parçalanması**

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[1:5]

array([2, 3, 4, 5])

In [6]:
arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[:4]

array([1, 2, 3, 4])

In [8]:
arr[::2]

array([1, 3, 5, 7, 9])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:3] = 25

In [11]:
arr = np.arange(1,10)

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr2 = arr # Aynı değerleri gösteren iki tane değişken

In [14]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2[:3] =  25

In [16]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [17]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [18]:
arr = np.arange(1,10)

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arrCopy = arr.copy() # Değerler kopyalanıyor.

In [21]:
arrCopy[:3] = 25

In [22]:
arrCopy

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
newArray = np.arange(1,21)

In [25]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
newArray = newArray.reshape(4,5)

In [27]:
newArray[0,0]

1

In [28]:
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [30]:
newArray[:2,:2]

array([[1, 2],
       [6, 7]])

In [31]:
newArray[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**Numpy Arraylerinin Filtrelenmesi**

In [32]:
arr = np.arange(1,10)

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [35]:
boolValuesArray = arr > 3

In [36]:
boolValuesArray

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [37]:
arr[boolValuesArray] # True olanlar filtrelenir.

array([4, 5, 6, 7, 8, 9])

In [38]:
arr[arr > 5] # Daha kısa hali.

array([6, 7, 8, 9])