**Numpy Arraylerinin Temel Operasyonları**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([2,3,4,5,6])

In [3]:
arr1

array([10, 20, 30, 40, 50])

In [4]:
arr2

array([2, 3, 4, 5, 6])

In [5]:
arr1 + arr2

array([12, 23, 34, 45, 56])

In [6]:
arr1 * arr2  # Inner Product(İç Çarpım)

array([ 20,  60, 120, 200, 300])

In [7]:
arr1 + 10

array([20, 30, 40, 50, 60])

In [8]:
arr1 - 10

array([ 0, 10, 20, 30, 40])

In [9]:
arr2 - 2

array([0, 1, 2, 3, 4])

In [10]:
arr1 / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [11]:
arr2 ** 2

array([ 4,  9, 16, 25, 36])

In [13]:
arr1

array([10, 20, 30, 40, 50])

In [14]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])