In [1]:
import numpy as np

In [2]:
#5 tane 1 barındıran bir array oluşturun
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
#5 tane 0 barındıran bir array oluşturun
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
#2'den 100'e kadar olan değerlerden 2'ye tam bölünebilenlerle bir array oluşturun
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [5]:
#5 tane 10 bulunan bir array oluşturun
np.ones(5) * 10 # Bir yöntemi daha bulunuyor. Bunu da kendiniz düşünmeye çalışın.

array([10., 10., 10., 10., 10.])

In [6]:
#1'den 16'ya kadar değer bulunduran 4x4'lük bir matris oluşturun
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
#4x4'lük bir birim matris oluşturun
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#0 ile 5 arasında rastgele değerler üretin
np.random.rand() * 5

0.16481128722740712

In [9]:
#5 x 5'lik bir matrisi Gaussian Distribution'a Göre (randn() fonksiyonu) değerler üreterek oluşturun
np.random.randn(25).reshape(5,5)

array([[-0.520274  ,  0.20062178,  0.08634372, -0.35061314, -1.03100119],
       [-0.23127804,  0.37562938,  0.31888846,  0.34940361, -0.57173435],
       [-0.70519928, -0.52018221, -0.90758678, -0.15822223, -0.50168649],
       [-0.76203751, -0.86818632,  2.12992808,  1.94056612, -1.25625307],
       [-0.90999172,  0.06046361,  2.17560708,  1.19127881,  1.25114036]])

In [10]:
#1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturun
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

**Array Indekslenmesi**

In [11]:
arr  = np.arange(1,101).reshape(10,10)

In [12]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Indeks işlemlerini kullanarak aşağıdaki sonucları elde etmeye çalışın

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],

       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],

       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])